[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true


[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true

[theme]
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1e293b"

